### ISSUE TITLE
Temporary source reopens only every other time

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/Parallax-IDE#234] opened 2015-08-17 22:10 UTC
New unsaved source code reopens in the app _only every other time_.  [Watch this video](https://drive.google.com/file/d/0B0tev9Y3WaL4UWI4N09RblhzZ3M/view?usp=sharing) for a demonstration.

This may be related to issue #231, #232, #235, and #236.

**Comment by phated** [comment] 2015-08-18 18:55
Duplicate of #231

**Closed as completed** 2015-08-25 19:53 UTC
Labels: Bug, Priority 1

**Comment by PropGit** [comment] 2015-08-30 00:07
Verified fixed via the same steps described in the demo video.
