### ISSUE TITLE
Seriously broken file storage and start of session recovery

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/Parallax-IDE#236] opened 2015-08-17 22:17 UTC
I don't even know how to describe the numerous problems I'm seeing with file creating, saving, and session restart.  Please [watch this video](https://drive.google.com/file/d/0B0tev9Y3WaL4MUJjeHAwdlQzMHM/view?usp=sharing) for demonstration of this file monkey business.

This may be related to issue #231, #232, #234, and #235.

**Comment by phated** [comment] 2015-08-18 18:53
This is a duplicate of #231

**Closed as completed** 2015-08-25 19:53 UTC
Labels: Bug, Priority 1

**Comment by PropGit** [comment] 2015-08-29 23:13
Verified fixed.  Ran the same tests (with the same code even) as in the demo video.
